### ISSUE TITLE
Thief raid-stolen skills missing in `/v2/skills`

### ISSUE THREAD

**Issue by shehi** [gw2-api/issues#72] opened 2024-01-21 13:02 UTC
### Current Behavior

_Re-reporting, originally from https://github.com/arenanet/api-cdi/issues/643_

The following skills are not available in `/v2/skills`:

Throw Magnetic Bomb (49112)
Soul Stone Venom (49052)
Detonate Plasma (49063)
Unstable Artifact (49123)

Also the case for some other non-raid stolen skills:
1113, 1114, 1119, 1116, 1149, 1134, 1132, 1120, 1121, 1126, 1127, 1130, 1133, 1135, 1146, 1138, 1144

### Expected Behavior

Although those skills are listed in Wiki, they are not available in API. I personally don't play Thief thus couldn't confirm, but API should have all the data eventually.

### Happening since

First reported in 2018

**Comment by greaka** [comment] 2024-01-21 13:04
Possible duplicate of #26

**Comment by shehi** [comment] 2024-01-21 13:13
Closing in favor of a simple comment https://github.com/gw2-api/issues/issues/26#issuecomment-1902625532

**Closed** 2024-01-21 13:14 UTC
Labels: bug, triage
