### ISSUE TITLE
/heropoints returns an empty list

### ISSUE THREAD

**Issue by T1000T** [gw2-api/issues#61] opened 2023-08-05 06:15 UTC
### Current Behavior

Hey, I'm requesting my character HP and get an empty list, https://api.guildwars2.com/v2/characters/[character_name]/heropoints/ I've placed my api key in the header and it works for other enpoints but not for heropoints. 

### Expected Behavior

get the info for the character, heropoints done.

### Steps To Reproduce

I've wrote an api call with my token to:
https://api.guildwars2.com/v2/characters/[character_name]/heropoints/
and it return: []

if i call other endpoints, it works, most of them.

### Happening since

first time i tried, somewhere in may 2023.

**Comment by darthmaim** [comment] 2023-08-07 07:57
Duplicate of #56

**Closed by darthmaim** 2023-08-07 07:57 UTC
Labels: bug, triage
