### ISSUE TITLE
`$.equipment_tabs.equipment.*.stats` field missing in `/api/v2/character/:id`

### ISSUE THREAD

**Issue by shehi** [gw2-api/issues#109] opened 2024-12-15 19:41 UTC
### Current Behavior

_Good Part_: Currently,_ `$.equipment.*.stats` field exists in `/api/v2/character/:id` in payload. This `stats` field contains important information about `stat_choices` selected on the current equipment piece.

![image](https://github.com/user-attachments/assets/c2176675-31de-4424-b129-d7701f36b6f8)

_Problem_: The same `stats` field is missing in `$.equipment_tabs.equipment.*.` which shouldn't be the case.

![image](https://github.com/user-attachments/assets/ca8238f1-ba83-4210-9a4d-f9a19ce95ec5)

[API Documentation](https://wiki.guildwars2.com/wiki/API:2/characters) is a little bit hazy about this. `$.equipment` bit is properly documented, `$.equipment_tabs` bit is not:

![image](https://github.com/user-attachments/assets/d9f314a0-f8e5-4cd4-8011-b75a0b0d250f)

![image](https://github.com/user-attachments/assets/955a6efb-7c8f-47ed-98b9-002a13984555)

### Expected Behavior

`$.equipment_tabs.equipment.*.stats` in `/api/v2/character/:id` should be added. It should contain the same information which exists in `$.equipment.*.stats` already.

### Steps To Reproduce

Any `/api/v2/character/:id` request where the character is wearing a gear with `stat_choices` .

**Comment by darthmaim** [comment] 2024-12-15 20:01
Duplicate of #12

**Closed by darthmaim** 2024-12-15 20:01 UTC
Labels: bug, triage
